Added a Dockerfile
flavio-fernandes/mqtt2kasa pull request #4
Opened 2021-08-02 11:41 UTC by johnjones4

Thanks for this project! I'm planning to use it with a little home automation bot I'm working on and I'm setting it all up to run in containers. Therefore, I added a Dockerfile.

2021-08-02 13:01 UTC, flavio-fernandes requested changes
This is great! Thank you so much for using it and suggesting this PR to make it more useful for folks using containers.
I have a few suggestions and asks, if you do not mind.
Best,
-- flaviof

2021-08-02 13:01 UTC, flavio-fernandes commented on Dockerfile
> +COPY requirements.txt requirements.txt
If you did the copy on line 9 here instead, would you still need this extra copy?

2021-08-02 13:01 UTC, flavio-fernandes commented on Dockerfile
> +RUN pip3 install -r requirements.txt
NIT: you can just do

```pip3 install .``` 

instead, right?

2021-08-02 13:01 UTC, flavio-fernandes commented on Dockerfile
> +CMD ["python3", "-m", "mqtt2kasa.main"]
Could you please add some comments either here or in the README file on how you use docker the Volumes (-v)?

I suspect it will help a lot of folks on customizing their yaml file and accessing it as a "read only" mount for their Docker based deployments. If you have not done much of that, I can help too.

2021-12-23 12:49 UTC, snh commented on Dockerfile
> +COPY requirements.txt requirements.txt
By just copying in `requirements.txt` on its own, changes to the rest of the project won't cause the Docker layer that the `pip` sourced dependencies are installed in to be invalidated, except of course if `requirements.txt` itself changes as well.

https://pythonspeed.com/articles/docker-caching-model/ gives a practical example of the benefits of separating out `requirements.txt`.

2021-12-26 22:41 UTC, flavio-fernandes commented on Dockerfile
> +COPY requirements.txt requirements.txt
Make sense. Thanks for the PR! And I hope you are enjoying your Kasa gizmos!

2021-12-26 22:47 UTC, flavio-fernandes requested changes

2021-12-26 22:47 UTC, flavio-fernandes commented on mqtt2kasa/log.py
> +    log_to_console()
johnjones4  hm... looks like `_log_handler_address` is not working for you, right? I normally use that and wonder if there is a way to make it work for you w/out removing it completely.

2023-10-20 23:16 UTC, flavio-fernandes commented
This has been open for a while. I'm closing it for now.
@johnjones4 please let me know if you want to take another attempt on this.

2023-10-20 23:16 UTC, closed without merging